version: '3.4'

services:
  clienttst1:
    image: clienttst1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes: 
      - .:/usr/src/app


volumes: 
  data:
