version: '3.4'

services:
  clienttst1:
    image: clienttst1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      - '/app/node_modules'


volumes: 
  data:
